#' print.design_comparison
#' Print function for design comparison.
#' @param design_comparison A comparison generated by compare_designs.
#' @param display c("highlights", "all", "none"), where highlights is the default.
#' @param output_type c("html", "pdf", "word", "github", "Rmd", "none"). Creates a file called 'design_comparison.html' unless file_prefix is provided (or a different file type is specified). 'Rmd' means write R markdown only (otherwise Rmd is saved along with desired type of output file).
#' @param file_prefix Optional. If provided, names the file specified by 'output_type.' 
#' @param render_quietly If FALSE (default), preview pops up and rendering details display to console. 
#' @method print design_comparison
#' @importFrom knitr kable
#' @importFrom rmarkdown render
#' @export
print.design_comparison <- function(design_comparison, 
                                    display = c("highlights", "all", "none"),
                                    output_type = c("html", "pdf", "word", "github", "Rmd", "none"),
                                    file_prefix = "design_comparison", 
                                    render_quietly = FALSE){
  
  print_dc(dc = design_comparison,
           display =  match.arg(display, c("highlights", "all", "none")),
           file_prefix = file_prefix,
           output_type = match.arg(output_type, c("html", "pdf", "word", "github", "Rmd", "none")),
           render_quietly = render_quietly)
  # to_Rmd deliberately left blank so that print_dc() can call print.design_comparison() recursively properly
}

# internal version of print.design_copy
# to_Rmd is just a dummy telling print helper functions to add backticks
print_dc <- function(dc, display, file_prefix = "design_comparison", output_type = "html", to_Rmd = FALSE, render_quietly = FALSE){
  
  if(output_type != "none" && !to_Rmd){
    
    ########################## YAML ##############################################
    header <- c("---", 
                "title: DeclareDesign Comparisons", 
                "output:",
                "      OUTPUTTYPE_document:", 
                "           toc: true",
                "           number_sections: true",
                "---")
    header <- gsub("OUTPUTTYPE", output_type, header)
    if(output_type == "word" || output_type == "github")
      header <- header[-6] # check for alternate syntax for number_sections
      
    body <- capture.output(print_dc(dc, display, file_prefix, output_type, to_Rmd = TRUE))
    file_name <- paste0(file_prefix, ".Rmd")
    writeLines(c(header, body), file_name)
    cat("DeclareDesign RMarkdown comparison template created. The file is called ", 
        file_name, ".\n", sep="")
    
    if(output_type != "Rmd"){
      render(file_name, quiet = render_quietly)
      cat(output_type, "document rendered sucessfully.\n")
    }
      
    
  }else{
    
    if(display != "none"){
    ########################## INTRO TEXT #########################################
      
      md("Overview of comparisons of ", dc$N_designs, "designs", N_hashtags = 1) # top of outline
      
      # md() is markdown-friendly wrapper for cat()
      
      ############## HOW MANY STEPS? ###############################################

      if(difference(dc$steps_per_design)){
        
        md("Designs included in comparison: ", 
           paste(dc$design_names, collapse = ", "), ".", sep="")
        print_md(t(dc$steps_per_design), to_Rmd = to_Rmd)
        
      }else{
        
        md("Designs included in comparison: ", paste(dc$design_names, collapse = ", "),
           ".\nEach design has ", unique(dc$steps_per_design), " steps. ", 
           sep="", trail_breaks = 1)
        
      }
      md("Design steps compared: ", paste(colnames(dc$similarity), collapse = ", "), 
         ".\nComparisons below are made to ", dc$reference_design, ".", 
         lead_breaks = 0, sep="")
      
      if(mean(dc$summary_available) != 1){
        md("Errors", N_hashtags = 2)
        md("The following errors were caught while making summaries:", 
           trail_breaks = 2)
        for(i in which(!(dc$summary_available))){
          md(dc$design_names[i], 
             "generated the following error:", lead_breaks = 0, trail_breaks = 0)
          md(dc$summaries[[i]], lead_breaks = 0, trail_breaks = 0)
        }
      }
      
    } 
    
    if(display == "all") {
      
      md("Tests for Equality", N_hashtags = 2)
      print_md(dc$equality_comparisons, to_Rmd = to_Rmd)
      
      
      md("Number of Characters", N_hashtags = 2)
      
      if(sum(unlist(lapply(dc$overview_nchar, difference)))){
        md("Number of characters for each design (by step in the code):", N_hashtags = 3)
        print_md(dc$overview_nchar, to_Rmd = to_Rmd)
      }else{
        if(display == "all"){
          md("Each design has same number of characters (by step in the code):", N_hashtags = 3)
          print_md(dc$overview_nchar[1,], to_Rmd = to_Rmd)
        }
      }
      
      md("Code Overview", N_hashtags = 2)
          md("This report compares the following designs: ", 
             paste(dc$design_names, collapse = ", "), ".", sep="")
          md("Number of steps per design:")
          print_md(kable(t(dc$steps_per_design)), to_Rmd = to_Rmd)
          
        }else{
          
          md("This report compares the following designs:", paste(dc$design_names, collapse = ", "),
             ".\nEach design has ", unique(dc$steps_per_design), " steps. ", 
             sep="", trail_breaks = 1)
         }

      md("When relevant, comparisons are made relative to ", dc$reference_design, ".", lead_breaks = 0, sep="")
      
      ########### WHICH STEPS COMPARED? #############################################

      md("Steps compared", N_hashtags = 2)
      md("Design steps compared: ", paste(colnames(dc$similarity), collapse = ", ")) 

      ########### CORE CODE DIFFERENCES #############################################
      
      md("Steps with differences in code", N_hashtags = 2)
      md("Summary of steps that exhibit some code differences across designs:")
      
      cd <- dc$code_differences
      diffs <- if(is.matrix(cd)) sum(matrix_difference(cd)) > 0 else length(cd) > 0

      if(diffs){ 
        print_md(rownames(dc$code_differences), to_Rmd = to_Rmd)
        md("Specifically:")
        print_md(kable(dc$code_differences), to_Rmd = to_Rmd)
        } else { print("Designs have same code")}
    
      ########### DETAIL STARTS HERE ############################################### 
      if(display == "all") {
      
      # md("Summaries", N_hashtags = 2)
      # could insert here and highlights version
      
    }else{
      if(display == "highlights"){
        md("Detail", N_hashtags = 1)      

        if(!is.null(dc$data_shape)){
          # Data structure
          md("Differences in Data structure", N_hashtags = 2)
          
          if(sum(matrix_difference(dc$data_shape))){ 
            print_md(kable(dc$data_shape), to_Rmd = to_Rmd)
          } else { print("Designs have same dimension")}
        }
  
        # Step Type Equality
        md("Tests for Equality Across Step Types", N_hashtags = 2)
        print_md(dc$equality_comparisons, to_Rmd = to_Rmd)
        
        # Code comparison
        md("Code Overview", N_hashtags = 2)
        
        for(i in 1:ncol(dc$overview)){
          md(colnames(dc$overview)[i], N_hashtags = 3, trail_breaks = 1)
          if(to_Rmd) cat("```\n")
          md(paste("\n\n", dc$design_names, ": ", dc$overview[,i], sep=""), 
             lead_breaks = 0)
          if(to_Rmd) cat("```\n")
        }
        

        }
}}}

# convenient markdown-style outlining of output
md <- function(a, b = NULL, c = NULL, d = NULL, e = NULL, f = NULL, g = NULL,
                    N_hashtags = 0, lead_breaks = 1, trail_breaks = 2, ...){

  cat(rep("\n", lead_breaks))
  cat(paste(rep("#", N_hashtags), collapse = ""), 
      a, b, c, d, e, f, g,
      rep("\n", trail_breaks), ...)
}

print_md <- function(..., to_Rmd = FALSE){
  
  if(to_Rmd) cat("```r\n")
  print(...)
  if(to_Rmd) cat("```\n")
  
}
